version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/desafio_boticario
      NODE_ENV: development
      PORT: 3333
    ports:
      - "3333:3333"
    command: npm run dev:server
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio_boticario
